name: Weekly Nightly Build

on:
  schedule:
    #- cron: '0 0 * * 3' # This runs only on THURSDAYS at midnight
    - cron: '20 1 9 10 *' # Runs Oct 8 at 22:20 ARG (01:20 UTC Oct 9)
env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read

concurrency:
  group: 'nightly-build-${{ github.ref }}'
  cancel-in-progress: false

jobs:
  nightly:
    strategy:
      fail-fast: false
      matrix:
        include:
          - submodule: rust-bitvmx-client
            clippy: true
            build_cpu: true
            dockerfile_path: tests/docker/Dockerfile
            docker_compose_path: tests/docker/docker-compose.yml

    uses: ./.github/workflows/ci_local_template.yml
    with:
      repo: 'FairgateLabs/rust-bitvmx-workspace'
      submodule_path: ${{ matrix.submodule }}
      cargo_lock_path: '${{ matrix.submodule }}/Cargo.lock'
      target_path: '${{ matrix.submodule }}/target'
      nightly: true
      clippy: ${{ matrix.clippy }}
      build_cpu: ${{ matrix.build_cpu }}
      docker_required: true
      dockerfile_path: ${{ matrix.dockerfile_path }}
      docker_compose_path: ${{ matrix.docker_compose_path }}
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}